### ISSUE TITLE
What's the accuracy of CIFAR100

### ISSUE THREAD

**Issue by ziqi-zhang** [ARiSE-Lab/DeepInspect#1]
Hi,

Thanks very much for sharing the awesome code with us. I'm trying to run the CIFAR100 code but I met a problem of the accuracy. When I run the code from https://github.com/aaron-xichen/pytorch-playground, the accuracy is only about 66%, but the reported accuracy is 74%. Did you ever meet a similar problem?

Thanks,

**Comment by yuchi1989** [comment]
Hi, they report 74% accuracy. Try this one from their website: http://ml.cs.tsinghua.edu.cn/~chenxi/pytorch-models/cifar100-3a55a987.pth

**Comment by ziqi-zhang** [comment]
Thanks for your reply!
